export const transactions = [
  {
    id: 1,
    title: "Amazon",
    type: "General Merchandise",
    owner: "Jeff Bezos",
    status: "Monday 12.22.2023",
    image: "/amazon.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: false,
  },
  {
    id: 2,
    title: "Num Pang",
    type: "General Merchandise",
    owner: "John Doe",
    status: "",
    image: "/num-pang.jpeg",
    amount: "$14.15",
    percent: "1.5% $0.22",
    isMissing: true,
  },
  {
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 3,
    title: "Amazon",
    type: "General Merchandise",
    owner: "Jeff Bezos",
    status: "Pending",
    image: "/amazon.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: false,
  },
  {
    id: 4,
    title: "Slack",
    type: "Chat",
    owner: "Jane Doe",
    status: "",
    image: "/slack.png",
    amount: "$14.15",
    percent: "1.7% $0.21",
    isMissing: true,
  },
  {
    id: 5,
    title: "Amazon",
    type: "General Merchandise",
    owner: "Jeff Bezos",
    status: "",
    image: "/amazon.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 6,
    title: "Amazon",
    type: "General Merchandise",
    owner: "Jeff Bezos",
    status: "",
    image: "/amazon.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: false,
  },
  {
    id: 7,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 8,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 9,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 10,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 11,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 12,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 13,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 14,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
  {
    id: 15,
    title: "Google",
    type: "Search Engine",
    owner: "Sergey Brin",
    status: "",
    image: "/google.png",
    amount: "$14.15",
    percent: "1.5% $0.21",
    isMissing: true,
  },
]